apiVersion: v1
kind: Namespace
metadata:
  name: blobe-staging
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: blobe-staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
