replicaCount: 1

image:
  repository: blobe/search-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3005
  type: ClusterIP

serviceAccount:
  roleArn: ""  # set per-env to IRSA ARN

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 70
