apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace | default "blobe" }}
data:
  PORT: "3003"
  NODE_ENV: "production"
  REGION: {{ .Values.global.region | default "us-east-1" | quote }}
