apiVersion: v2
name: kong-gateway
version: 1.0.0
description: Kong API Gateway sub-chart for Blobe services
dependencies:
  - name: kong
    version: "~2.26"
    repository: "https://charts.konghq.com"
