apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blobe-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SarangPKarun/blobeNative
    targetRevision: HEAD
    path: infra/helm/charts/blobe-services
    helm:
      valueFiles:
        - ../../../../infra/helm/values/us-east-1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blobe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
